name: netrartha_mobile
description: "Netrartha v1.0.2 - Outreach Eye Screening & Vision Center Tele-Ophthalmology Mobile App for Sankara Eye Foundation"
publish_to: "none"
version: 1.0.2+3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.0
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.9.0
  image_picker: ^1.0.7
  intl: ^0.19.0
  google_fonts: ^6.1.0
  connectivity_plus: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
